/*
 *
 */

package inko;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 1.2.2
 *
 */

import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class ArtikelFrame extends JFrame {

    private final MainFrame mainFrame;
    private final Random rand;

    public ArtikelFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        jArtikelComboBox.setModel( mainFrame.jArtikelComboBox.getModel() );
        jArtikelComboBoxActionPerformed(null);
        rand = new Random();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jNameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPZNField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSizeComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPackQuantityField = new javax.swing.JTextField();
        jCreateButton = new javax.swing.JButton();
        jCloseButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jArtikelComboBox = new javax.swing.JComboBox<>();
        jUpdateButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jAdvTextField1 = new gui.JAdvTextField();
        jDeleteButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTypeComboBox = new javax.swing.JComboBox<>();

        setTitle("Artikel Frame");

        jLabel1.setText("Name:");

        jLabel2.setText("PZN:");

        jLabel3.setText("Größe:");

        jSizeComboBox.setModel(new DefaultComboBoxModel(Size.values()));
        jSizeComboBox.setSelectedItem(Size.KEINE);
        jSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSizeComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Packungsinhalt:");

        jCreateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/add-16.png"))); // NOI18N
        jCreateButton.setText("Anlegen");
        jCreateButton.setToolTipText("Anlegen");
        jCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateButtonActionPerformed(evt);
            }
        });

        jCloseButton.setText("Schließen");
        jCloseButton.setToolTipText("Schließen");
        jCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCloseButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Artikel der Datenbank:");

        jArtikelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jArtikelComboBoxActionPerformed(evt);
            }
        });

        jUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/refresh-16.png"))); // NOI18N
        jUpdateButton.setText("Überschreiben");
        jUpdateButton.setToolTipText("Überschreiben");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });

        jAdvTextField1.setEditable(false);
        jAdvTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jDeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/remove-16.png"))); // NOI18N
        jDeleteButton.setText("Löschen");
        jDeleteButton.setToolTipText("Löschen");
        jDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Typ:");

        jTypeComboBox.setModel(new DefaultComboBoxModel(inko.ArtikelType.values()));
        jTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTypeComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCreateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jNameField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPZNField)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jTypeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                                    .addComponent(jSizeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPackQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jAdvTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jArtikelComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPZNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPackQuantityField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jArtikelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jAdvTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCreateButton)
                    .addComponent(jCloseButton)
                    .addComponent(jUpdateButton)
                    .addComponent(jDeleteButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public final void setHimi(Artikel himi) {
        jNameField.setText( himi.getName() );
        jPZNField.setText( String.valueOf( himi.getPZN() ));
        jPackQuantityField.setText( String.valueOf( himi.getPackQuantity() ));
        jSizeComboBox.setSelectedIndex( himi.getSize().ordinal() );
        jTypeComboBox.setSelectedIndex( himi.getType().ordinal() );
    }

    private void jCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateButtonActionPerformed
        Artikel himi = buildHimi();
        if ( exists( himi )) {
            jAdvTextField1.showError("Artikel mit PZN " + himi.getPZN() + " nicht angelegt, da bereits vorhanden.");
            return;
        }
        int affected;
        if (( affected = mainFrame.pio.insertArtikel( himi )) > 0 ) {
            jAdvTextField1.showSuccess("Eintrag erfolgreich angelegt.");
        } else {
            jAdvTextField1.showError( String.valueOf( affected ));
        }
        mainFrame.refreshArtikelComboBox();
        clearDialog();
    }//GEN-LAST:event_jCreateButtonActionPerformed

    private boolean exists(Artikel himi) {
        for ( Artikel h : mainFrame.pio.getArtikelList() ) {
            if ( h.getPZN() == himi.getPZN() ) {
                return true;
            }
        }
        return false;
    }

    private void clearDialog() {
        jNameField.setText("");
        jPZNField.setText("0");
        jSizeComboBox.setSelectedIndex(0);
        jPackQuantityField.setText("1");
        jSizeComboBoxActionPerformed(null);
    }

    private void jCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCloseButtonActionPerformed
        super.setVisible(false);
    }//GEN-LAST:event_jCloseButtonActionPerformed

    private Artikel buildHimi() {
        return new Artikel(
            jNameField.getText(),
            (Size) jSizeComboBox.getSelectedItem(),
            (ArtikelType) jTypeComboBox.getSelectedItem(),
            Integer.parseUnsignedInt( jPackQuantityField.getText() ),
            Integer.parseUnsignedInt( jPZNField.getText() )
        );
    }

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        Artikel himi = buildHimi();
        himi.setId(( (Artikel) jArtikelComboBox.getSelectedItem() ).getId() );
        int affected;
        if (( affected = mainFrame.pio.updateArtikel( himi )) == 1 ) {
            jAdvTextField1.showSuccess("Eintrag erfolgreich aktualisiert.");
        } else {
            jAdvTextField1.showError( String.valueOf( affected ));
        }
        mainFrame.refreshArtikelComboBox();
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void jDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButtonActionPerformed
        int option = JOptionPane.showConfirmDialog(
            this,
            "Das Löschen eines Artikels macht alle diese Einträge bei den Patienten ungültig!\n" +
                "Wirklich löschen?",
            "Artikel unwiderruflich löschen?",
            JOptionPane.YES_NO_OPTION
        );
        if ( option == JOptionPane.NO_OPTION ) {
            jAdvTextField1.showMessage("Speichern abgebrochen.");
            return;
        }
        boolean affected = mainFrame.pio.deleteHimi(( (Artikel) jArtikelComboBox.getSelectedItem() ).getId() );
        if (affected) {
            jAdvTextField1.showSuccess("Artikel gelöscht.");
        }
        mainFrame.refreshArtikelComboBox();
    }//GEN-LAST:event_jDeleteButtonActionPerformed

    private void jArtikelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jArtikelComboBoxActionPerformed
        if ( jArtikelComboBox.getSelectedItem() == null ) {
            return;
        }
        setHimi( (Artikel) jArtikelComboBox.getSelectedItem() );
        check4Comment();
    }//GEN-LAST:event_jArtikelComboBoxActionPerformed

    private void jSizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSizeComboBoxActionPerformed
        if ( jSizeComboBox.getSelectedItem() == Size.KEINE && jTypeComboBox.getSelectedItem() != ArtikelType.KOMMENTAR ) {
            jTypeComboBox.setSelectedItem( ArtikelType.VORLAGEN );
        }
    }//GEN-LAST:event_jSizeComboBoxActionPerformed

    private void jTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTypeComboBoxActionPerformed
        check4Comment();
    }//GEN-LAST:event_jTypeComboBoxActionPerformed

    private void check4Comment() {
        if ( jTypeComboBox.getSelectedItem().equals( ArtikelType.KOMMENTAR )) {
            jPZNField.setText( String.valueOf( rand.nextInt( 10*1000 )));
            jPZNField.setEnabled(false);
            jSizeComboBox.setSelectedItem( Size.KEINE );
            jSizeComboBox.setEnabled(false);
            jPackQuantityField.setText("1");
            jPackQuantityField.setEnabled(false);
        } else {
            jPZNField.setText("");
            jPZNField.setEnabled(true);
            jSizeComboBox.setEnabled(true);
            jPackQuantityField.setText("");
            jPackQuantityField.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.JAdvTextField jAdvTextField1;
    private javax.swing.JComboBox<inko.Artikel> jArtikelComboBox;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JButton jCloseButton;
    private javax.swing.JButton jCreateButton;
    private javax.swing.JButton jDeleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNameField;
    private javax.swing.JTextField jPZNField;
    private javax.swing.JTextField jPackQuantityField;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jSizeComboBox;
    private javax.swing.JComboBox<String> jTypeComboBox;
    private javax.swing.JButton jUpdateButton;
    // End of variables declaration//GEN-END:variables

}
