/*
 *
 */

package inko;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 2.0.0
 *
 */

import dataformat.csv.CSV;
import dataformat.csv.Parser;
import static inko.PatientField.ADG_FIELDS;
import static inko.PatientField.ID;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import util.ColorLibrary;

public class CompareFrame extends javax.swing.JFrame {

    private int leftindex = -1, rightindex = -1;
    private final TableModel table;
    private final ArrayList<Patient> csv_patienten = new ArrayList<>();
    private final MainFrame mainframe;
    private final Color[][] colorArray;

    public CompareFrame(MainFrame mainframe, File csvfile) {
        initComponents();
        colorArray = new Color[jTable1.getRowCount()][jTable1.getColumnCount()];
        this.mainframe = mainframe;
        table = jTable1.getModel();
        importCSV(csvfile);
    }

    class ColoringCellRenderer extends DefaultTableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(
            JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col
        ) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
            setHorizontalAlignment(CENTER);
            if (( colorArray != null ) && ( colorArray[row][col] != null )) {
                setBackground( getColor( colorArray[row][col], row ));
            } else {
                setBackground( getDefaultColor( row ));
            }
            return this;
        }
        private Color getDefaultColor(int row) {
            if ( row%2 == 0 ) {
                return Color.WHITE;
            }
            return ColorLibrary.LIGHT_GRAY;
        }
        private Color getColor(Color color, int row) {
            if ( row%2 == 0 ) {
                return color.brighter();
            }
            return color;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonNextRight = new javax.swing.JButton();
        jButtonADG = new javax.swing.JButton();
        jButtonADGSelect = new javax.swing.JButton();
        jButtonADGNew = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabelRight = new javax.swing.JLabel();
        jLabelLeft = new javax.swing.JLabel();
        jButtonNextLeft = new javax.swing.JButton();
        jButtonBackLeft = new javax.swing.JButton();
        jButtonBackRight = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        statusField = new gui.JAdvTextField();
        jButtonDeleteRight = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Vergleichsfenster");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Inko DB", "Feld", "ADG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDefaultRenderer(Object.class, new ColoringCellRenderer());
        jTable1.setCellSelectionEnabled(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButtonNextRight.setText("weiter");
        jButtonNextRight.setEnabled(false);
        jButtonNextRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextRightActionPerformed(evt);
            }
        });

        jButtonADG.setText("ADG komplett übernehmen");
        jButtonADG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADGActionPerformed(evt);
            }
        });

        jButtonADGSelect.setText("ADG-Selektion übernehmen");
        jButtonADGSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADGSelectActionPerformed(evt);
            }
        });

        jButtonADGNew.setText("Als neuen Kunden anlegen");
        jButtonADGNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADGNewActionPerformed(evt);
            }
        });

        jButtonClose.setText("Schließen");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabelRight.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelRight.setText("Nr.");

        jLabelLeft.setText("Nr.");

        jButtonNextLeft.setText("weiter");
        jButtonNextLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextLeftActionPerformed(evt);
            }
        });

        jButtonBackLeft.setText("zurück");
        jButtonBackLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackLeftActionPerformed(evt);
            }
        });

        jButtonBackRight.setText("zurück");
        jButtonBackRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackRightActionPerformed(evt);
            }
        });

        jToggleButton1.setText("verbinden");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        statusField.setEditable(false);
        statusField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButtonDeleteRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/delete_icon.png"))); // NOI18N
        jButtonDeleteRight.setToolTipText("Eintrag aus Liste entfernen");
        jButtonDeleteRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelRight, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNextLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(jButtonBackLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonADGSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                            .addComponent(jButtonBackRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonADG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonNextRight, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                                    .addComponent(jButtonADGNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteRight))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statusField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDeleteRight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLeft)
                            .addComponent(jLabelRight)))
                    .addComponent(jToggleButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonNextRight)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNextLeft)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonBackLeft)
                                .addComponent(jButtonBackRight)))
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonADG)
                            .addComponent(jButtonADGSelect))
                        .addGap(6, 6, 6)
                        .addComponent(jButtonADGNew))
                    .addComponent(jButtonClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNextRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextRightActionPerformed
        if ( rightindex+1 < csv_patienten.size() ) {
            ++rightindex;
            if ( jToggleButton1.isSelected() ) {
                jButtonNextLeftActionPerformed(null);
            }
            compareRight();
        }
    }//GEN-LAST:event_jButtonNextRightActionPerformed

    private void jButtonADGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADGActionPerformed
        transfereID();
        int linesChanged = mainframe.pio.updatePatient( csv_patienten.get(rightindex), ADG_FIELDS );
        --leftindex;
        csv_patienten.remove(rightindex);
        --rightindex;
        jButtonNextRightActionPerformed(null);
        showStatus(linesChanged);
    }//GEN-LAST:event_jButtonADGActionPerformed

    private void jButtonADGNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADGNewActionPerformed
        int linesChanged = mainframe.pio.insertPatient( csv_patienten.get( rightindex ));
        csv_patienten.remove(rightindex);
        --rightindex;
        jButtonNextRightActionPerformed(null);
        showStatus(linesChanged);
    }//GEN-LAST:event_jButtonADGNewActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        super.setVisible(false);
        mainframe.reloadPatients();
    }//GEN-LAST:event_formWindowClosing

    private void transfereID() {
        // ID des ADG-Eintrages auf DB-Eintrag setzen
        csv_patienten.get(rightindex).set( ID, mainframe.getPatients().get(leftindex).getId() );
    }

    private void jButtonADGSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADGSelectActionPerformed
        transfereID();
        int[] rows = jTable1.getSelectedRows();
        List<PatientField> list = new ArrayList<>();
        for (int i = 0; i < rows.length; ++i) {
            // generiert das Pattern-Feld der zu aktualisierenden Werte
            list.add( PatientField.ADG_FIELDS.get( i ));
        }
        int linesChanged = mainframe.pio.updatePatient( csv_patienten.get(rightindex), list );
        csv_patienten.remove(rightindex);
        --rightindex;
        jButtonNextRightActionPerformed(null);
        showStatus(linesChanged);
    }//GEN-LAST:event_jButtonADGSelectActionPerformed

    private void jButtonNextLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextLeftActionPerformed
        if ( leftindex+1 < mainframe.getPatients().size() ) {
            ++leftindex;
            compareLeft();
        }
    }//GEN-LAST:event_jButtonNextLeftActionPerformed

    private void jButtonBackRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackRightActionPerformed
        if ( rightindex-1 >= 0 ) {
            --rightindex;
            if ( jToggleButton1.isSelected() ) {
                jButtonBackLeftActionPerformed(null);
            }
            compareRight();
        }
    }//GEN-LAST:event_jButtonBackRightActionPerformed

    private void jButtonBackLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackLeftActionPerformed
        if ( leftindex-1 >= 0 ) {
            --leftindex;
            compareLeft();
        }
    }//GEN-LAST:event_jButtonBackLeftActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if ( jToggleButton1.isSelected() ) {
            jButtonNextLeft.setEnabled(false);
            jButtonBackLeft.setEnabled(false);
        } else {
            jButtonNextLeft.setEnabled(true);
            jButtonBackLeft.setEnabled(true);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButtonDeleteRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRightActionPerformed
        csv_patienten.remove(rightindex);
        --rightindex;
        jButtonNextRightActionPerformed(null);
    }//GEN-LAST:event_jButtonDeleteRightActionPerformed

    private void showStatus(int linesChanged) {
        if (linesChanged > 0) {
            statusField.showSuccess( linesChanged + " Zeilen verarbeitet." );
        } else {
            statusField.showSuccess( "Keine Daten verarbeitet." );
        }
    }

    private void importCSV(File csvfile) {
        CSV csv;
        try {
            csv = new CSV(
                new dataformat.csv.Reader( csvfile, Charset.forName( "Cp1252" ), new Parser( "\t", false )), true
            );
            ArrayList<ArrayList<String>> dataset = csv.getDataset();
            for ( ArrayList<String> entry : dataset ) {
                csv_patienten.add( Patient.fromADG( entry.toArray( new String[0] )));
            }
            activateUI();
        } catch (IOException e) {
            jButtonADG.setEnabled(false);
            jButtonADGSelect.setEnabled(false);
            jButtonADGNew.setEnabled(false);
            jButtonDeleteRight.setEnabled(false);
            jButtonBackRight.setEnabled(false);
            statusField.showError( e.getMessage() );
            mainframe.statusField.showError("Lesen der Datei fehlgeschlagen (I/O Fehler)");
            System.err.println( e.toString() );
        }
    }

    private void activateUI() {
        for (int i = 0; i < ADG_FIELDS.size(); ++i) {
            table.setValueAt( ADG_FIELDS.get(i).getUIName(), i, 1 );
        }
        jButtonNextLeftActionPerformed(null);
        jButtonNextRightActionPerformed(null);
        jButtonNextRight.setEnabled(true);
    }

    private void mapTableData(Patient patient, int tableColumn) {
        for (int i = 0; i < ADG_FIELDS.size(); ++i) {
            table.setValueAt( patient.getFormattedValue( ADG_FIELDS.get( i )), i, tableColumn);
            coloringTable(i);
        }
    }

    private void compareRight() {
        mapTableData( csv_patienten.get( rightindex ), 2 );
        jLabelRight.setText("Nr.: " + rightindex);
    }

    private void compareLeft() {
        mapTableData( mainframe.getPatients().get( leftindex ), 0 );
        jLabelLeft.setText("Nr.: " + leftindex);
    }

    private void coloringTable(int index) {
        try {
            if ( table.getValueAt( index, 0 ).equals( table.getValueAt( index, 2 ))) {
                colorArray[index][0] = ColorLibrary.LIGHT_GREEN;
                colorArray[index][2] = ColorLibrary.LIGHT_GREEN;
            } else {
                colorArray[index][0] = ColorLibrary.LIGHT_RED;
                colorArray[index][2] = ColorLibrary.LIGHT_RED;
            }
        } catch (NullPointerException e) {}
        jTable1.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonADG;
    private javax.swing.JButton jButtonADGNew;
    private javax.swing.JButton jButtonADGSelect;
    private javax.swing.JButton jButtonBackLeft;
    private javax.swing.JButton jButtonBackRight;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonDeleteRight;
    private javax.swing.JButton jButtonNextLeft;
    private javax.swing.JButton jButtonNextRight;
    private javax.swing.JLabel jLabelLeft;
    private javax.swing.JLabel jLabelRight;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private gui.JAdvTextField statusField;
    // End of variables declaration//GEN-END:variables

}
