/*
 *
 */

package inko;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 1.0.3
 *
 */

import java.awt.EventQueue;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

public class InfoFrame extends JFrame implements HasPatient {

    public final static String SERVER = "localhost";

    private Patient patient;
    private DBio pio;
    private DefaultComboBoxModel patientComboBoxModel = new DefaultComboBoxModel();
    private String server = SERVER;

    private final DefaultListModel<Artikel> listModel = new DefaultListModel<>();

    public InfoFrame(String server) {
        if (server != null) {
            this.server = server;
        }
        initComponents();
        initMoreComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inko Info");

        jComboBox1.setModel(patientComboBoxModel);

        jList1.setModel(listModel);
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setCellRenderer(new ArtikelListCellRenderer());
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initMoreComponents() {
        pio = new DBio( server, DBio.DEFAULT_PORT, new net.Login( MainFrame.user, MainFrame.pass ));
        if ( !pio.connect() ) {
            System.err.println("Datenbank antwortet nicht!");
            int x = this.getContentPane().getComponentCount();
            for ( int i = 0; i < x; ++i) {
                this.getContentPane().getComponent(i).setEnabled(false);
            }
            return;
        }
        patientComboBoxModel = MainFrame.getNewPatientComboBoxModel(jComboBox1, pio, this);
        jComboBox1.setSelectedIndex(0);
        pio.close();
    }

    @Override
    public void setPatient(Patient patient) {
        this.patient = patient;
        listModel.removeAllElements();
        for ( Artikel h : patient.getArtikelList() ) {
            listModel.addElement(h);
        }
    }

    @Override
    public Patient getPatient() {
        return patient;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String[] args) {
        if ( args == null || args.length <= 0 ) {
            exec(SERVER);
        } else if ( !args[0].startsWith( "--" )) {
            exec(args[0]);
        } else if ( args[0].startsWith( "--server" )) {
            exec( args[0].substring( 8 ));
        } else {
            System.out.println("Parameter " + Arrays.toString(args) + " unbekannt.");
        }
    }

    private static void exec(String server) {
        System.out.println("INFO: DB: " + server + ":" + SQLConnection.DEFAULT_PORT);
        EventQueue.invokeLater( () -> {
            new InfoFrame(server).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Patient> jComboBox1;
    private javax.swing.JList<Artikel> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
