/*
 *
 */

package inko;

/**
 *
 * @author  Martin Pröhl alias MythGraphics
 * @version 5.0.0
 *
 */

import com.google.zxing.WriterException;
import static inko.Document.*;
import static inko.InkoType.*;
import static inko.PatientField.*;
import static inko.SignableDocument.*;
import java.awt.Color;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.KeyboardFocusManager;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.*;
import javax.swing.*;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.plaf.basic.BasicArrowButton;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.text.JTextComponent;
import static util.Net.getLocalIpAddress;
import static util.QRCodeGenerator.generateQRCodeImage;

public class MainFrame extends JFrame {

    public final static String NAME     = "MythGraphics InkoProgramm";
    public final static String VERSION  = "6.0.0";
    public final static DateFormat DF   = new SimpleDateFormat("dd.MM.yyyy");
    public final static Color RED       = new Color(255,102,102);
    public final static Color GREEN     = new Color(51,255,51);

    public static String SEVENZIP       = "C:\\Program Files\\7-Zip\\7z.exe";
    public static String OO             = "P:\\OpenOffice 4\\program\\soffice.exe";
//  public static String OO             = "C:\\Program Files (x86)\\OpenOffice 4\\program\\soffice.exe";
    public static String CSVFILESTR     = "C:\\TEMP\\REPORT.TXT"; // ADG trennt mit Tabulator!
    public static String IP_PATTERN     = "";

    public final String outpath;

    protected static String server      = "localhost";
    protected static String user        = "mythg";
    protected static char[] pass        = new char[0];

    protected DBio pio;
    protected PatientTableModel patientTableModel;
    protected PatientComboBoxModel patientComboBoxModel;

    private final DefaultComboBoxModel<Artikel> artikelComboBoxModel = new DefaultComboBoxModel<>();
    private final PatientArtikelListModel patientArtikelListModel    = new PatientArtikelListModel();

    private SettlementFrame orteFrame;
    private CompareFrame compareFrame;
    private ArtikelFrame artikelFrame;
    private String insurenceInfo = "";
    private boolean isAdjusting  = false;
    private SignatureServer signServer;

    public MainFrame() {
        outpath = System.getProperty("user.dir") + "\\Inko-Dokumente\\";
        System.out.println("INFO: outpath: " + outpath);
        System.out.println("INFO: OO: " + OO);
        System.out.println("INFO: 7z: " + SEVENZIP);
        System.out.println("INFO: DB: " + server + ":" + SQLConnection.DEFAULT_PORT);
        System.out.println("INFO: IP-Pattern: " + IP_PATTERN);
        initDBCon();
        initComponents();
        initPatientComboBox();
        initMoreComponents();
    }

    private static void printHelp() {
        System.out.println("Parameter:");
        System.out.println("  --7z[path]            Pfad zur 7z.exe");
        System.out.println("  --oo[path]            Pfad zur soffice.exe (OpenOffice)");
        System.out.println("  --server[ip]          DB-Server an Port " + SQLConnection.DEFAULT_PORT);
        System.out.println("                        (Port nicht änderbar)");
        System.out.println("  --firststart          legt die Datenbank-Struktur an");
        System.out.println("  --updateDB            aktualisiert die Datenbank von Version 5 auf 6");
        System.out.println("  --ipPattern[pattern]  IP-Pattern des Netzwerks für den Signatur-Server");
        System.out.println("  --user                Benutzernamen für die Datenbank");
        System.out.println("  --pass                Passwort für die Datenbank");
        System.out.println("  --info                Zeigt den InfoFrame an");
        System.out.println("  --ui                  Zeigt den MainFrame an (optional)");
        System.out.println("  --oldDBui             Zeigt den MainFrame für das \"ALTE\" DB-Format an");
        System.out.println("  --help / -?           zeigt diese Hilfe");
        System.out.println("  --version             zeigt Programm-Version");
        System.out.println();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup1 = new javax.swing.ButtonGroup();
        artikelPanel = new javax.swing.JPanel();
        jAddArtikelButton = new javax.swing.JButton();
        jArtikelComboBox = getArtikelComboBox();
        jChangeArtikelButton = new javax.swing.JButton();
        jRemoveArtikelButton = new javax.swing.JButton();
        aRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        kRadioButton = new javax.swing.JRadioButton();
        sRadioButton = new javax.swing.JRadioButton();
        jCreateArtikelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPatientArtikelList = new javax.swing.JList<>();
        jUpButton = new BasicArrowButton(BasicArrowButton.NORTH);
        jDownButton = new BasicArrowButton(BasicArrowButton.SOUTH);
        patientPanel = new javax.swing.JPanel();
        liefernCheckBox = new javax.swing.JCheckBox();
        freiCheckBox = new javax.swing.JCheckBox();
        jYearChooser = new com.toedter.calendar.JYearChooser();
        pauseCheckBox = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = getJTable();
        statusField = new gui.JAdvTextField();
        patientComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        insurenceTextField = new javax.swing.JTextField();
        newButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        deckblattButton = new javax.swing.JButton();
        BeratungsbogenButton = new javax.swing.JButton();
        BindungserklärungButton = new javax.swing.JButton();
        MehrkostenerklärungButton = new javax.swing.JButton();
        etikettenButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRxFaelligButton = new javax.swing.JButton();
        jFaelligButton = new javax.swing.JButton();
        jBindFaelligButton = new javax.swing.JButton();
        lieferlisteButton = new javax.swing.JButton();
        patientenlisteButton = new javax.swing.JButton();
        jButtonArtikelListe = new javax.swing.JButton();
        jButtonArtikelListe2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLocationButton = new javax.swing.JButton();
        jButtonADG = new javax.swing.JButton();
        jButtonNewRx = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonSignBeratung = new javax.swing.JButton();
        jButtonSignBindung = new javax.swing.JButton();
        jButtonSignMehrkosten = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(NAME + " v" + VERSION);
        setSize(new java.awt.Dimension(1000, 750));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jAddArtikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/add-16.png"))); // NOI18N
        jAddArtikelButton.setToolTipText("Artikel hinzufügen");
        jAddArtikelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddArtikelButtonActionPerformed(evt);
            }
        });

        jArtikelComboBox.setEditable(true);
        jArtikelComboBox.setModel(artikelComboBoxModel);

        jChangeArtikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/refresh-16.png"))); // NOI18N
        jChangeArtikelButton.setToolTipText("Artikel ändern");
        jChangeArtikelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangeArtikelButtonActionPerformed(evt);
            }
        });

        jRemoveArtikelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/remove-16.png"))); // NOI18N
        jRemoveArtikelButton.setToolTipText("Artikel entfernen");
        jRemoveArtikelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveArtikelButtonActionPerformed(evt);
            }
        });

        aRadioButton.setText("ableitend");
        aRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aRadioButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Artikelauswahl:");

        kRadioButton.setText("saugend (Kind)");
        kRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kRadioButtonActionPerformed(evt);
            }
        });

        sRadioButton.setSelected(true);
        sRadioButton.setText("saugend");
        sRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sRadioButtonActionPerformed(evt);
            }
        });

        jCreateArtikelButton.setText("Artikel anlegen / ändern");
        jCreateArtikelButton.setToolTipText("öffnet den Artikeldialog");
        jCreateArtikelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateArtikelButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Menge:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99, 1));

        jLabel3.setText("Artikel:");

        jPatientArtikelList.setModel(patientArtikelListModel);
        jPatientArtikelList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jPatientArtikelList.setCellRenderer(new inko.ArtikelListCellRenderer());
        jScrollPane2.setViewportView(jPatientArtikelList);

        jUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpButtonActionPerformed(evt);
            }
        });

        jDownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDownButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout artikelPanelLayout = new javax.swing.GroupLayout(artikelPanel);
        artikelPanel.setLayout(artikelPanelLayout);
        artikelPanelLayout.setHorizontalGroup(
            artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artikelPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(artikelPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(artikelPanelLayout.createSequentialGroup()
                        .addComponent(jAddArtikelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRemoveArtikelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jChangeArtikelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(sRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aRadioButton))
                    .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, artikelPanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, artikelPanelLayout.createSequentialGroup()
                            .addComponent(jArtikelComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jCreateArtikelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        artikelPanelLayout.setVerticalGroup(
            artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(artikelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(artikelPanelLayout.createSequentialGroup()
                        .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jArtikelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(artikelPanelLayout.createSequentialGroup()
                                .addComponent(jCreateArtikelButton)
                                .addGap(7, 7, 7)
                                .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jAddArtikelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jRemoveArtikelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jChangeArtikelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(artikelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(sRadioButton)
                                        .addComponent(kRadioButton)
                                        .addComponent(aRadioButton))))
                            .addComponent(jDownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        liefernCheckBox.setText("monatlich liefern");
        liefernCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liefernCheckBoxActionPerformed(evt);
            }
        });

        freiCheckBox.setText("frei bis:");
        freiCheckBox.setToolTipText("ZuZahlungsBefreiung");
        freiCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freiCheckBoxActionPerformed(evt);
            }
        });

        jYearChooser.setEnabled(false);

        pauseCheckBox.setText("pausiert");
        pauseCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseCheckBoxActionPerformed(evt);
            }
        });

        jTable1.setRowHeight(22);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jTable1);

        statusField.setEditable(false);
        statusField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusField.setFocusable(false);
        statusField.setRequestFocusEnabled(false);

        jLabel7.setText("Patient:");

        saveButton.setForeground(new java.awt.Color(0, 51, 255));
        saveButton.setText("Patient speichern");
        saveButton.setToolTipText("Eintrag in DatenBank speichern");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        deleteButton.setForeground(new java.awt.Color(255, 0, 0));
        deleteButton.setText("Patient löschen");
        deleteButton.setToolTipText("Patient aus DatenBank unwiderruflich löschen");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Krankenkasse:");

        insurenceTextField.setEditable(false);
        insurenceTextField.setBackground(new java.awt.Color(255, 255, 255));
        insurenceTextField.setToolTipText("Für mehr Infos anklicken.");
        insurenceTextField.setPreferredSize(new java.awt.Dimension(6, 25));
        insurenceTextField.setRequestFocusEnabled(false);
        insurenceTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insurenceTextFieldMouseClicked(evt);
            }
        });

        newButton.setForeground(new java.awt.Color(0, 153, 0));
        newButton.setText("Patient anlegen");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/info-16.png"))); // NOI18N
        infoButton.setToolTipText("Infos anzeigen");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout patientPanelLayout = new javax.swing.GroupLayout(patientPanel);
        patientPanel.setLayout(patientPanelLayout);
        patientPanelLayout.setHorizontalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(statusField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(patientPanelLayout.createSequentialGroup()
                        .addComponent(liefernCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(freiCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pauseCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientPanelLayout.createSequentialGroup()
                        .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(patientPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE))
                            .addGroup(patientPanelLayout.createSequentialGroup()
                                .addComponent(insurenceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        patientPanelLayout.setVerticalGroup(
            patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(liefernCheckBox)
                        .addComponent(freiCheckBox))
                    .addComponent(jYearChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pauseCheckBox)
                        .addComponent(saveButton)
                        .addComponent(deleteButton)
                        .addComponent(newButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(patientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insurenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        deleteButton.getAccessibleContext().setAccessibleDescription("");
        insurenceTextField.getAccessibleContext().setAccessibleName("KrankenkassenFeld");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        deckblattButton.setText("Deckblatt");
        deckblattButton.setToolTipText("Deckblatt erzeugen");
        deckblattButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deckblattButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deckblattButton);

        BeratungsbogenButton.setText("Beratungsbogen");
        BeratungsbogenButton.setToolTipText("Beratungsbogen erzeugen");
        BeratungsbogenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeratungsbogenButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BeratungsbogenButton);

        BindungserklärungButton.setText("Bindungserklärung");
        BindungserklärungButton.setToolTipText("Bindungserklärung erzeugen");
        BindungserklärungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BindungserklärungButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BindungserklärungButton);

        MehrkostenerklärungButton.setText("Erklärung zu Mehrkosten");
        MehrkostenerklärungButton.setToolTipText("Mehrkostenerklärung erzeugen");
        MehrkostenerklärungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MehrkostenerklärungButtonActionPerformed(evt);
            }
        });
        jPanel1.add(MehrkostenerklärungButton);

        etikettenButton.setText("Lieferetiketten");
        etikettenButton.setToolTipText("Lieferetikettenbogen erzeugen");
        etikettenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etikettenButtonActionPerformed(evt);
            }
        });
        jPanel1.add(etikettenButton);
        etikettenButton.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane1.addTab("Basis", jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jRxFaelligButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/rezept_icon.png"))); // NOI18N
        jRxFaelligButton.setToolTipText("Fälligkeitsliste Rezepte");
        jRxFaelligButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRxFaelligButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jRxFaelligButton);

        jFaelligButton.setForeground(new java.awt.Color(0, 153, 0));
        jFaelligButton.setText("Fälligkeitsliste");
        jFaelligButton.setToolTipText("Fälligkeitsliste Rezept- und Bindungserklärungen");
        jFaelligButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFaelligButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jFaelligButton);

        jBindFaelligButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inko/bindung_icon.png"))); // NOI18N
        jBindFaelligButton.setToolTipText("Fälligkeitsliste Bindungserklärungen");
        jBindFaelligButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBindFaelligButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jBindFaelligButton);

        lieferlisteButton.setForeground(new java.awt.Color(0, 153, 0));
        lieferlisteButton.setText("Lieferliste");
        lieferlisteButton.setToolTipText("Lieferliste erzeugen");
        lieferlisteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lieferlisteButtonActionPerformed(evt);
            }
        });
        jPanel2.add(lieferlisteButton);

        patientenlisteButton.setForeground(new java.awt.Color(0, 153, 0));
        patientenlisteButton.setText("Patientenliste");
        patientenlisteButton.setToolTipText("Patientenliste erzeugen");
        patientenlisteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientenlisteButtonActionPerformed(evt);
            }
        });
        jPanel2.add(patientenlisteButton);

        jButtonArtikelListe.setForeground(new java.awt.Color(0, 153, 0));
        jButtonArtikelListe.setText("Artikel-Liste");
        jButtonArtikelListe.setToolTipText("HiMi-Liste erzeugen");
        jButtonArtikelListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArtikelListeActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonArtikelListe);

        jButtonArtikelListe2.setForeground(new java.awt.Color(0, 153, 0));
        jButtonArtikelListe2.setText("große Artikel-Liste");
        jButtonArtikelListe2.setToolTipText("große HiMi-Liste erzeugen");
        jButtonArtikelListe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArtikelListe2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonArtikelListe2);

        jTabbedPane1.addTab("Listen", jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jLocationButton.setForeground(new java.awt.Color(204, 0, 204));
        jLocationButton.setText("Orte-Dialog");
        jLocationButton.setToolTipText("Orte-Dialog öffnen");
        jLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLocationButtonActionPerformed(evt);
            }
        });
        jPanel3.add(jLocationButton);

        jButtonADG.setForeground(new java.awt.Color(204, 0, 204));
        jButtonADG.setText("Kundenabgleich ADG");
        jButtonADG.setToolTipText("Kundenabgleich ADG öffnen");
        jButtonADG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonADGActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonADG);

        jButtonNewRx.setForeground(new java.awt.Color(204, 0, 204));
        jButtonNewRx.setText("Dialog 'Neues Rezept'");
        jButtonNewRx.setToolTipText("neues-Rezept-Dialog öffnen");
        jButtonNewRx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewRxActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonNewRx);

        jTabbedPane1.addTab("Sonstiges", jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jButtonSignBeratung.setText("Beratungsbogen");
        jButtonSignBeratung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignBeratungActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonSignBeratung);

        jButtonSignBindung.setText("Bindungserklärung");
        jButtonSignBindung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignBindungActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonSignBindung);

        jButtonSignMehrkosten.setText("Erklärung zu Mehrkosten");
        jButtonSignMehrkosten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignMehrkostenActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonSignMehrkosten);

        jTabbedPane1.addTab("Unterschriften", jPanel4);

        jMenu1.setText("Artikel");

        jMenuItem15.setText("Artikel anlegen / ändern");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Patient");

        jMenuItem19.setForeground(new java.awt.Color(0, 153, 51));
        jMenuItem19.setText("anlegen");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);

        jMenuItem16.setForeground(new java.awt.Color(0, 51, 255));
        jMenuItem16.setText("speichern");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);
        jMenu2.add(jSeparator1);

        jMenuItem17.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem17.setText("löschen");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem17);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Druck");

        jMenu4.setText("Basis");

        jMenuItem1.setText("Deckblatt");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Bindungserklärung");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Mehrkostenerklärung");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Beratungsbogen");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Lieferetiketten");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenu3.add(jMenu4);

        jMenu5.setText("Listen");

        jMenu7.setText("Fälligkeitslisten");

        jMenuItem8.setText("Rezepte");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenuItem9.setText("Bindungserklärungen");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem10.setText("kombinierte Liste");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenu5.add(jMenu7);

        jMenu8.setText("Artikellisten");

        jMenuItem11.setText("Artikelliste");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuItem12.setText("große Artikelliste");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenu5.add(jMenu8);

        jMenuItem6.setText("Patientenliste");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Lieferliste");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu3.add(jMenu5);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Sonstiges");

        jMenuItem13.setText("Kundenabgleich ADG");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuItem14.setText("Orte-Dialog");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenuItem18.setText("Neues-Rezept-Dialog");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(artikelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(artikelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(patientPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        if (args.length == 0) {
            showGUI();
            return;
        }
        switch (args[0]) {
            case "--dateformat":
                try {
                    System.out.println( DF.format( args[1] )); // fehlt der Wert "Tag", wird der letzte Tag des Monats gesetzt
                }
                catch (IllegalArgumentException | NoSuchElementException e) {
                    System.err.println( args[1] + " ungültig.");
                    System.err.println( "Datum unverständlich - Format unbekannt." );
                    System.err.println( e.getMessage() );
                }
                return;
            case "--help":
                printHelp();
                return;
            case "-?":
                printHelp();
                return;
            case "--version":
                System.out.println(NAME + " v" + VERSION);
                return;
        }
        for (int i = 0; i < args.length; ++i) {
            if ( args[i].startsWith( "--7z" )) {
                SEVENZIP = args[i].substring(4);
            }
            else if ( args[i].startsWith( "--oo" )) {
                OO = args[i].substring(4);
            }
            else if ( args[i].startsWith( "--server" )) {
                server = args[i].substring(8);
            }
            else if ( args[i].startsWith( "--user" )) {
                user = args[i].substring(6);
            }
            else if ( args[i].startsWith( "--pass" )) {
                pass = args[i].substring(6).toCharArray();
            }
            else if ( args[i].startsWith( "--ipPattern" )) {
                IP_PATTERN = args[i].substring(11);
            }
            else if ( args[i].equals( "--firststart" )) {
                String user;
                char[] pass;
                System.out.println("Starte Initiallisierung der Datenbank ...");
                System.out.print("Benutzer: ");
                try ( Scanner scanner = new Scanner( System.in )) {
                    user = scanner.next().trim();
                }
                System.out.print("Passwort: ");
                pass = System.console().readPassword();
                System.out.println("initiallisieren ...");
                DBio.firstRun(user, pass, server);
                System.out.println("... abgeschlossen.");
                return;
            }
            else if ( args[i].startsWith( "--updateDB" )) {
                System.out.println("Starte Update der Datenbank ...");
                DBio.updateDB(user, pass, server);
                System.out.println("... abgeschlossen.");
            }
            else if ( args[i].startsWith( "--info" )) {
                InfoFrame.main( new String[]{server} );
                return;
            }
            else if ( args[i].startsWith( "--ui" )) {
                showGUI();
                return;
            }
            else if ( args[i].startsWith( "--oldDBui" )) {
                inko.old.OldMainFrame.main(null);
                return;
            }
        }
        showGUI();
    }

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteEntry();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void etikettenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etikettenButtonActionPerformed
        processTemplate("Adressetiketten.odt");
    }//GEN-LAST:event_etikettenButtonActionPerformed

    protected void loadEntry(Patient patient) {
        if (patient == null) {
            return;
        }
        Patient currentPatient = patient;
        if ( patient.getId() != -1 ) {
            currentPatient = pio.getPatientById( patient.getId() ); // lädt die aktuellen Patienten-Daten aus der DB
        }

        if (currentPatient == null) {
            System.err.println("loadEntry: currentPatient ist NULL");
            return;
        }

        patientTableModel.setPatient(currentPatient);
        patientArtikelListModel.setPatient(currentPatient);
        loadEntryUpdateUI(currentPatient);
    }

    protected void loadEntryUpdateUI(Patient patient) {
        liefernCheckBox.setSelected( patient.toDeliver() );
        pauseCheckBox.setSelected( patient.isPaused() );

        freiCheckBox.setSelected( patient.isCoPaymentFree() );
        freiCheckBoxActionPerformed(null);
        jYearChooser.setValue( patient.getCoPaymentFreeUntil().getYear() );

        insurenceTextField.setText( patient.getHealthInsurer() );
        setTypeUI();
        typeChangeActionPerformed();

        if ( patient.hasSignatureData() ) {
            if ( patient.getSignature(BERATUNG) != null && patient.getSignature(BERATUNG).getSign() != null ) {
                BeratungsbogenButton.setBackground(GREEN);
            } else {
                BeratungsbogenButton.setBackground(RED);
            }
            if ( patient.getSignature(BINDUNG) != null && patient.getSignature(BINDUNG).getSign() != null ) {
                BindungserklärungButton.setBackground(GREEN);
            } else {
                BindungserklärungButton.setBackground(RED);
            }
            if ( patient.getSignature(MEHRKOSTEN) != null && patient.getSignature(MEHRKOSTEN).getSign() != null ) {
                MehrkostenerklärungButton.setBackground(GREEN);
            } else {
                MehrkostenerklärungButton.setBackground(RED);
            }
        }

        refreshArtikelComboBox();
        jTable1.requestFocus();
        jTable1.editCellAt(1, 1);

        patient.setModified(false);
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        saveEntry( patientTableModel.getPatient() );
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteEntry() {
        int option = JOptionPane.showConfirmDialog(
            this,
            "Patient unwiderruflich löschen?",
            "Absicht?",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE
        );
        if (option != JOptionPane.YES_OPTION) {
            return;
        }
        Patient p = (Patient) patientComboBox.getSelectedItem();
        boolean success = pio.deletePatient( p.getId() );
        if (success) {
            patientComboBox.removeItem(p);
            statusField.showSuccess("Eintrag \"" + p.toString() + "\" gelöscht.");
        }
    }

    private void setTypeUI() {
        switch ( patientTableModel.getPatient().getType() ) {
            case ABLEITEND:     aRadioButton.setSelected(true); break;
            case SAUGEND:       sRadioButton.setSelected(true); break;
            case SAUGEND_KIND:  kRadioButton.setSelected(true); break;
        }
    }

    protected void saveEntry(Patient patient) {
        if (patient == null) {
            statusField.showError("Kein Patient zum Speichern geladen.");
            return;
        }
        else if ( !patient.isModified() ) {
            statusField.showProblem("Keine Änderung an Patient erkannt. Speichern nicht erforderlich.");
            return;
        }
        try {
            pio.savePatient(patient);
            statusField.showSuccess( "Patient " + patient.getFullName() + " erfolgreich in Datenbank gespeichert." );
            patientComboBoxModel.updateSelectedDisplay(patientComboBox);
        } catch (Exception e) {
            statusField.showError( "Fehler beim Speichern: " + e.getMessage() );
            e.printStackTrace();
        }
    }

    private void BeratungsbogenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeratungsbogenButtonActionPerformed
        makeHtml(evt, BERATUNGSBOGEN);
    }//GEN-LAST:event_BeratungsbogenButtonActionPerformed

    private void BindungserklärungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BindungserklärungButtonActionPerformed
        makeHtml(evt, BINDUNGSERKLÄRUNG);
    }//GEN-LAST:event_BindungserklärungButtonActionPerformed

    private void MehrkostenerklärungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MehrkostenerklärungButtonActionPerformed
        makeHtml(evt, MEHRKOSTENERKLÄRUNG);
    }//GEN-LAST:event_MehrkostenerklärungButtonActionPerformed

    private void deckblattButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deckblattButtonActionPerformed
        makeHtml(evt, DECKBLATT);
    }//GEN-LAST:event_deckblattButtonActionPerformed

    private void jFaelligButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFaelligButtonActionPerformed
        makeHtml(evt, FÄLLIGKEITSLISTE);
    }//GEN-LAST:event_jFaelligButtonActionPerformed

    private void lieferlisteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lieferlisteButtonActionPerformed
        makeHtml(evt, LIEFERLISTE);
    }//GEN-LAST:event_lieferlisteButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        quit();
    }//GEN-LAST:event_formWindowClosing

    private void quit() {
        pio.close();
        if (orteFrame != null) {
            orteFrame.dispose();
        }
        if (artikelFrame != null) {
            artikelFrame.dispose();
        }
        if (compareFrame != null) {
            compareFrame.dispose();
        }
        if (signServer != null) {
            signServer.stopServer(0);
        }
        super.dispose();
        System.exit(0);
    }

    private void patientenlisteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientenlisteButtonActionPerformed
        makeHtml(evt, PATIENTENLISTE);
    }//GEN-LAST:event_patientenlisteButtonActionPerformed

    protected void makeHtml(ActionEvent evt, Document doc) {
        HTMLMaker htmlmaker = new HTMLMaker( doc.getFileName(), outpath+doc.getFileName() );
        try {
            switch (doc) {
                case PATIENTENLISTE:
                    htmlmaker.makePatientList( patientComboBoxModel.getList() );
                    break;
                case HIMILISTE:
                    htmlmaker.makeArtikelList( patientComboBoxModel.getList(), pio.getArtikelList() );
                    break;
                case HIMILISTE2:
                    htmlmaker.makeArtikelList2( patientComboBoxModel.getList() );
                    break;
                case DECKBLATT:
                    htmlmaker.makeFrontpage( patientTableModel.getPatient() );
                    break;
                case BERATUNGSBOGEN:
                    htmlmaker.makeSignableDocument( patientTableModel.getPatient(), BERATUNG );
                    break;
                case BINDUNGSERKLÄRUNG:
                    htmlmaker.makeSignableDocument( patientTableModel.getPatient(), BINDUNG );
                    break;
                case MEHRKOSTENERKLÄRUNG:
                    htmlmaker.makeSignableDocument( patientTableModel.getPatient(), MEHRKOSTEN );
                    break;
                case LIEFERLISTE:
                    htmlmaker.makeDeliveryList( patientComboBoxModel.getList() );
                    break;
                case FÄLLIGKEITSLISTE:
                    htmlmaker.makeExpiringList( patientComboBoxModel.getList(), HTMLMaker.EXPIRINGLIST );
                    break;
                case FÄLLIGKEITSLISTE_RX:
                    htmlmaker.makeExpiringList( patientComboBoxModel.getList(), HTMLMaker.EXPIRINGLIST_RX );
                    break;
                case FÄLLIGKEITSLISTE_BIND:
                    htmlmaker.makeExpiringList( patientComboBoxModel.getList(), HTMLMaker.EXPIRINGLIST_BIND );
                    break;
            }
        } catch (IOException e) {
            statusField.showError(HTMLMaker.IOERROR);
            e.printStackTrace();
        }
    }

    private void sRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sRadioButtonActionPerformed
        typeChangeActionPerformed();
    }//GEN-LAST:event_sRadioButtonActionPerformed

    private void aRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aRadioButtonActionPerformed
        typeChangeActionPerformed();
    }//GEN-LAST:event_aRadioButtonActionPerformed

    private void freiCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freiCheckBoxActionPerformed
        if ( freiCheckBox.isSelected() ) {
            jYearChooser.setEnabled(true);
            jYearChooser.setValue( Calendar.getInstance().get( Calendar.YEAR ));
            patientTableModel.getPatient().set( BEFREIUNGSDATUM, Patient.parseDate( "31.12." + jYearChooser.getValue() ));
        } else {
            jYearChooser.setEnabled(false);
            patientTableModel.getPatient().set( BEFREIUNGSDATUM, Patient.DEFAULT_DATE );
        }
        if (evt == null) {
            // von der Initialisierungsroutine aufgerufen
            patientTableModel.getPatient().setModified(false);
        }
    }//GEN-LAST:event_freiCheckBoxActionPerformed

    private void jButtonArtikelListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArtikelListeActionPerformed
        makeHtml(evt, HIMILISTE);
    }//GEN-LAST:event_jButtonArtikelListeActionPerformed

    private void jButtonNewRxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewRxActionPerformed
        RezeptDialog dialog = new RezeptDialog(this);
        dialog.setVisible(true);
        if ( dialog.hasChanged() ) {
            patientTableModel.getPatient().set( RX_DATE, Patient.parseDate( dialog.jTextField_RxDate.getText() ));
            patientTableModel.getPatient().set(
                END_OF_LICENCE_DATE, Patient.parseDate( dialog.jTextField_RxExpiringDate.getText()
            ));
            patientTableModel.fireTableDataChanged();
            dialog.dispose();
        }
    }//GEN-LAST:event_jButtonNewRxActionPerformed

    private void jLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLocationButtonActionPerformed
        if (orteFrame == null) {
            orteFrame = new SettlementFrame(this);
        }
        orteFrame.setVisible(true);
    }//GEN-LAST:event_jLocationButtonActionPerformed

    private void kRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kRadioButtonActionPerformed
        typeChangeActionPerformed();
    }//GEN-LAST:event_kRadioButtonActionPerformed

    private void jButtonADGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonADGActionPerformed
        compareFrame = new CompareFrame( this, new File( CSVFILESTR ));
        compareFrame.setVisible(true);
    }//GEN-LAST:event_jButtonADGActionPerformed

    private void jButtonArtikelListe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArtikelListe2ActionPerformed
        makeHtml(evt, HIMILISTE2);
    }//GEN-LAST:event_jButtonArtikelListe2ActionPerformed

    private void jRxFaelligButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRxFaelligButtonActionPerformed
        makeHtml(evt, FÄLLIGKEITSLISTE);
    }//GEN-LAST:event_jRxFaelligButtonActionPerformed

    void refreshArtikelComboBox() {
        jArtikelComboBox.removeAllItems();
        pio.getArtikelList().forEach( h -> jArtikelComboBox.addItem( h ));
    }

    private void jBindFaelligButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBindFaelligButtonActionPerformed
        makeHtml(evt, FÄLLIGKEITSLISTE_BIND);
    }//GEN-LAST:event_jBindFaelligButtonActionPerformed

    private void jCreateArtikelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateArtikelButtonActionPerformed
        if (artikelFrame == null) {
            artikelFrame = new ArtikelFrame(this);
        }
        String md5sum;
        char[] password;
        // Passwort-Eingabe holen
        JPasswordField passfield = new JPasswordField();
        // Fokus-Logik hinzufügen
        passfield.addAncestorListener( new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                // Fordert den Fokus an, sobald das JPasswordField sichtbar wird
                passfield.requestFocusInWindow();
            }
            @Override
            public void ancestorRemoved(AncestorEvent event) {}
            @Override
            public void ancestorMoved(AncestorEvent event) {}
        });
        int okCxl = JOptionPane.showConfirmDialog(
            this, passfield, "Passwort eingeben", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE
        );
        if (okCxl == JOptionPane.OK_OPTION) {
            password = passfield.getPassword();
        } else {
            return;
        }
        // md5sum berechnen
        try {
            MessageDigest digest = MessageDigest.getInstance("MD5");
            byte[] input = String.valueOf(password).getBytes();
            byte[] hash = digest.digest(input);
            // in Hex-String konvertieren
            StringBuilder hexString = new StringBuilder();
            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if ( hex.length() == 1 ) {
                    hexString.append('0');
                }
                hexString.append( hex.toUpperCase() );
            }
            md5sum = hexString.toString();
//          System.out.println( "Hash der Eingabe: " + md5sum ); // debug
        } catch (NoSuchAlgorithmException e) {
            System.err.println( e.getMessage() );
            return;
        }
        // Passwort-Hash aus DB holen
        String dbHash = String.valueOf( pio.getArtikelPasswordHash() );
//      System.out.println( "gespeicherter Hash (DB): " + dbHash ); // debug
        // Hashes vergleichen
        if ( dbHash.equalsIgnoreCase( md5sum )) {
            statusField.showSuccess("Passwort OK.");
            artikelFrame.setVisible(true);
        } else {
            statusField.showError("Passwort falsch.");
        }
    }//GEN-LAST:event_jCreateArtikelButtonActionPerformed

    protected void _jAddArtikelButtonActionPerformed(ActionEvent evt) {
        if ( jArtikelComboBox.getSelectedIndex() >= 0 ) {
            Artikel artikel = (( Artikel ) jArtikelComboBox.getSelectedItem() );
            artikel.setMenge(( Integer ) jSpinner1.getValue() );
            patientArtikelListModel.addElement(artikel);
        }
    }

    protected void _jRemoveArtikelButtonActionPerformed(ActionEvent evt) {
        if ( jPatientArtikelList.getSelectedIndex() >= 0 ) {
            patientArtikelListModel.remove( jPatientArtikelList.getSelectedIndex() );
        }
    }

    protected void _jChangeArtikelButtonActionPerformed(ActionEvent evt) {
        if ( jPatientArtikelList.getSelectedIndex() >= 0 ) {
            Artikel artikel = (( Artikel ) jArtikelComboBox.getSelectedItem() ).clone();
            artikel.setMenge(( Integer ) jSpinner1.getValue() );
            patientArtikelListModel.set( jPatientArtikelList.getSelectedIndex(), artikel );
        }
    }

    private void pauseCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseCheckBoxActionPerformed
        patientTableModel.getPatient().set( PAUSE, pauseCheckBox.isSelected() );
    }//GEN-LAST:event_pauseCheckBoxActionPerformed

    private void liefernCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liefernCheckBoxActionPerformed
        patientTableModel.getPatient().set( DELIVER, liefernCheckBox.isSelected() );
    }//GEN-LAST:event_liefernCheckBoxActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        jCreateArtikelButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        saveEntry( patientTableModel.getPatient() );
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        deleteButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        deckblattButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        BindungserklärungButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        MehrkostenerklärungButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        BeratungsbogenButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        etikettenButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        jFaelligButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        jRxFaelligButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jBindFaelligButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        jButtonArtikelListeActionPerformed(null);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        jButtonArtikelListe2ActionPerformed(null);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        patientenlisteButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        lieferlisteButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        jButtonADGActionPerformed(null);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        jLocationButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        jButtonNewRxActionPerformed(null);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void insurenceTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insurenceTextFieldMouseClicked
        infoButtonActionPerformed(null);
    }//GEN-LAST:event_insurenceTextFieldMouseClicked

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        newButtonActionPerformed(null);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        Patient patient = new Patient();
        patient.set( LAST_NAME, "[namenlos]" );
        patientComboBoxModel.addElement(patient);
        patientComboBox.setSelectedItem(patient);
        loadEntry(patient);
    }//GEN-LAST:event_newButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        if ( !insurenceInfo.isEmpty() ) {
            JOptionPane.showMessageDialog(this, insurenceInfo);
        }
    }//GEN-LAST:event_infoButtonActionPerformed

    protected void jPatientArtikelListMouseClicked(MouseEvent evt) {
        if ( jPatientArtikelList.getSelectedIndex() > -1 ) {
            Artikel artikel = jPatientArtikelList.getSelectedValue();
            if (artikel != null) {
                jSpinner1.setValue( artikel.getMenge() );
                jArtikelComboBox.setSelectedItem(artikel);
            }
        }
    }

    private void jAddArtikelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddArtikelButtonActionPerformed
        _jAddArtikelButtonActionPerformed(evt);
    }//GEN-LAST:event_jAddArtikelButtonActionPerformed

    private void jRemoveArtikelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveArtikelButtonActionPerformed
        _jRemoveArtikelButtonActionPerformed(evt);
    }//GEN-LAST:event_jRemoveArtikelButtonActionPerformed

    private void jChangeArtikelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangeArtikelButtonActionPerformed
        _jChangeArtikelButtonActionPerformed(evt);
    }//GEN-LAST:event_jChangeArtikelButtonActionPerformed

    private void jDownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDownButtonActionPerformed
        jPatientArtikelList.setSelectedIndex(
            patientArtikelListModel.moveElementDown(
                jPatientArtikelList.getSelectedIndex()
        ));
    }//GEN-LAST:event_jDownButtonActionPerformed

    private void jUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpButtonActionPerformed
        jPatientArtikelList.setSelectedIndex(
            patientArtikelListModel.moveElementUp(
                jPatientArtikelList.getSelectedIndex()
        ));
    }//GEN-LAST:event_jUpButtonActionPerformed

    private void sign(int patientId, SignableDocument document) {
        startServer();
        showQRCode(patientId, document);
    }

    private void startServer() {
        if (signServer == null) {
            signServer = new SignatureServer(this);
            try {
                signServer.startServer();
            } catch (IOException e) {
                statusField.showError( e.getMessage() );
                e.printStackTrace();
            }
        }
    }

    private void showQRCode(int patientId, SignableDocument document) {
        String localIp = getLocalIpAddress(IP_PATTERN);
        String url = "http://" + localIp + ":" + SignatureServer.PORT +
                     "/signature?patientId=" + patientId + "?document=" + document;
        System.out.println("Signatur-URL: " + url); // debug
        try {
            BufferedImage qrCodeImage = generateQRCodeImage(url, 300, 300);
            EventQueue.invokeLater( () -> {
                JLabel qrLabel = new JLabel( new ImageIcon( qrCodeImage ));
                // im eigenen JDialog anzeigen
                JOptionPane.showMessageDialog(
                    this,
                    qrLabel,
                    "Bitte mit dem Tablet scannen",
                    JOptionPane.PLAIN_MESSAGE
                );
            });
        } catch (WriterException e) {
            statusField.showError("Generieren des QR-Codes fehlgeschlagen.");
            e.printStackTrace();
        }
    }

    private void jButtonSignBeratungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignBeratungActionPerformed
        sign( patientTableModel.getPatient().getId(), SignableDocument.BERATUNG );
    }//GEN-LAST:event_jButtonSignBeratungActionPerformed

    private void jButtonSignBindungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignBindungActionPerformed
        sign( patientTableModel.getPatient().getId(), SignableDocument.BINDUNG );
    }//GEN-LAST:event_jButtonSignBindungActionPerformed

    private void jButtonSignMehrkostenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignMehrkostenActionPerformed
        sign( patientTableModel.getPatient().getId(), SignableDocument.MEHRKOSTEN );
    }//GEN-LAST:event_jButtonSignMehrkostenActionPerformed

    private void selectPZN(String ref) {
        int refValue;
        try {
            refValue = Integer.parseInt(ref);
        } catch (NumberFormatException e) {
            return;
        }
        ComboBoxModel<Artikel> model = jArtikelComboBox.getModel();
        for (int i = 0; i < model.getSize(); ++i) {
            if ( model.getElementAt(i).getPZN() == refValue ) {
                jArtikelComboBox.setSelectedIndex(i);
                return;
        }}
    }

    protected void jArtikelComboBoxEditorKeyReleased(KeyEvent evt) {
        if ( evt == null || evt.getKeyCode() == KeyEvent.VK_ENTER ) {
            selectPZN((( JTextComponent ) jArtikelComboBox.getEditor().getEditorComponent() ).getText() );
        }
    }

    private void jArtikelComboBoxEditorMouseClicked(MouseEvent evt) {
        if ( evt.getClickCount() >= 2 ) {
            // Doppelklick
            if ( evt.getComponent() instanceof JTextComponent ) {
                JTextComponent textEditor = (JTextComponent) evt.getComponent();
                textEditor.setText("");
                textEditor.requestFocusInWindow();
            }
        }
    }

    private void typeChangeActionPerformed() {
        Patient patient = patientTableModel.getPatient();
        if ( aRadioButton.isSelected() ) {
            patient.setType(ABLEITEND);
        }
        else if ( sRadioButton.isSelected() ) {
            patient.setType(SAUGEND);
        }
        else if ( kRadioButton.isSelected() ) {
            patient.setType(SAUGEND_KIND);
        }
        insurenceTextField.setText( patient.getHealthInsurer() );
        insurenceInfo = patient.getBesonderheiten();
    }

    public void processTemplate(String template) {
        String newODTname = outpath +
                            template.substring(0, template.length()-4) +
                            " " +
                            patientComboBox.getSelectedItem() +
                            ".odt";
        new DocumentWorker( template, newODTname, patientTableModel.getPatient(), this ).execute();
    }

    protected static void showGUI(JFrame guiFrame) {
        EventQueue.invokeLater( () -> {
            guiFrame.setVisible(true);
        });
    }

    private static void showGUI() {
        showGUI( new MainFrame() );
    }

    protected DBio getDBio() {
        return new DBio( server, DBio.DEFAULT_PORT, new net.Login( user, pass ));
    }

    final void initDBCon() {
        if ( pio != null ) {
            pio.close();
        }
        pio = getDBio();
        if ( pio != null && pio.connect() ) {
            ArrayList<String> list = pio.getSettlements();
            if ( list != null && !list.isEmpty() ) {
                Location.ORTE = list; // nicht schön, aber funzt!
            }
        } else {
            System.err.println("Datenbank antwortet nicht!");
            statusField.showError("Datenbank antwortet nicht!");
            int x = this.getContentPane().getComponentCount();
            for ( int i = 0; i < x; ++i) {
                this.getContentPane().getComponent(i).setEnabled(false);
            }
        }
    }

    private void setupEnterTraversal(JTable table) {
        // eine neue Action für die Enter-Taste definieren
        InputMap inputMap = table.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        ActionMap actionMap = table.getActionMap();

        // KeyStroke für Enter abfangen
        KeyStroke enter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
        inputMap.put(enter, "selectNextColumnCell"); // interner Namen für "nächste Zelle"

        // eigener Action-Handler für mehr Kontrolle
        actionMap.put("selectNextColumnCell", new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int row = table.getSelectedRow();
                int col = table.getSelectedColumn();

                // wenn wir in der Eingabe-Spalte (1) sind:
                if ( col == 1 ) {
                    // falls wir in der letzten Zeile sind, zur ersten Zeile
                    if ( row == table.getRowCount()-1 ) {
                        table.changeSelection(1, 1, false, false);
                    } else {
                        // eine Zeile runter
                        table.changeSelection(row+1, 1, false, false);
                    }
                    // sofort den Edit-Modus für die neue Zelle starten
                    table.editCellAt( table.getSelectedRow(), 1 );
                    Component editor = table.getEditorComponent();
                    if (editor != null) {
                        editor.requestFocus();
                    }
                }
            }
        });
    }

    private JTable getJTable() {
        patientTableModel = new PatientTableModel();
        JTable jTable = new JTable(patientTableModel) {
            private final PatientTableCellRenderer customRenderer = new PatientTableCellRenderer();
            @Override
            public TableCellRenderer getCellRenderer(int row, int column) {
                return customRenderer;
            }
            @Override
            public TableCellEditor getCellEditor(int row, int column) {
                if (column == 1) {
                    // PatientField für die aktuelle Zeile aus der Liste des Modells holen
                    PatientField field = UI_FIELDS.get(row);
                    // wähle den Editor basierend auf dem Feldtyp im Enum
                    if (field.getType() == LocalDate.class) {
                        return new LocalDateCellEditor();
                    } else if (field == TYP) {
                        return new DefaultCellEditor( new JComboBox<>( InkoType.values() ));
                    }
                    // ... weitere Spezialfälle ...
                }
                return super.getCellEditor(row, column);
            }
        };
        setupEnterTraversal(jTable);
        jTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        return jTable;
    }

    private void addArtikelComboBoxEditorListeners() {
        Component editorComponent = jArtikelComboBox.getEditor().getEditorComponent();
        editorComponent.addKeyListener( new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent evt) {
                jArtikelComboBoxEditorKeyReleased(evt);
            }
        });
        editorComponent.addMouseListener( new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                jArtikelComboBoxEditorMouseClicked(evt);
            }
        });
    }

    private void initMoreComponents() {
        addArtikelComboBoxEditorListeners();

        jPatientArtikelList.addMouseListener( new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                jPatientArtikelListMouseClicked(evt);
            }
        });

        // init radioGroup1
        radioGroup1.add(aRadioButton);
        radioGroup1.add(sRadioButton);
        radioGroup1.add(kRadioButton);

        UIManager.put("CheckBox.disabledText", Color.BLACK);

        new File(outpath).mkdir();

        KeyboardFocusManager.getCurrentKeyboardFocusManager().addPropertyChangeListener( "permanentFocusOwner", e -> {
            Object newValue = e.getNewValue();
            if (newValue instanceof JTextField) {
                JTextField textField = (JTextField) newValue;
                SwingUtilities.invokeLater(textField::selectAll); // selectAll() ans Ende der Event-Queue schieben
            }
        });
    }

    protected List<Patient> getPatients() {
        return patientComboBoxModel.getList();
    }

    protected void reloadPatients() {
        patientComboBoxModel.refresh( pio.getPatientList() );
    }

    protected JComboBox<Artikel> getArtikelComboBox() {
        return new JComboBox<>();
    }

    private void initPatientComboBox() {
        patientComboBoxModel = getNewPatientComboBoxModel(patientComboBox, pio, patientTableModel, patientArtikelListModel);

        // zusätzliche ActionListener für patientComboBox hinzufügen
        patientComboBox.addActionListener( e -> {
            if (isAdjusting) {
                // Verhindert Endlosschleifen
                return;
            }

            Object item = patientComboBox.getSelectedItem();
            Patient selected;
            /* Wenn die ComboBox editierbar ist, gibt getSelectedItem() oft nur einen String
             * (den getippten Text) zurück, statt des Patient-Objekts.
             */
            if (item instanceof Patient) {
                selected = (Patient) item;
            } else {
                return;
            }

            // prüfen, ob der aktuell geladene Patient geändert wurde
            Patient patient = patientTableModel.getPatient();
            if ( patient != null && patient.isModified() ) {
                int choice = JOptionPane.showConfirmDialog(
                    this,
                    "Änderungen an " + patient.getFullName() + " speichern?",
                    "Änderungen speichern?",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.WARNING_MESSAGE
                );
                if (choice == JOptionPane.YES_OPTION) {
                    saveEntry(patient);
                } else if (choice == JOptionPane.CANCEL_OPTION) {
                    isAdjusting = true;
                    patientComboBoxModel.setSelectedItem(patient); // zurücksetzen
                    isAdjusting = false;
                    return;
                }
            }

            // neuen Patienten ins Formular laden
            loadEntry(selected);
        });

        patientComboBox.setSelectedIndex(0);
    }

    static PatientComboBoxModel getNewPatientComboBoxModel(final JComboBox<Patient> jComboBox, DBio pio, HasPatient... user) {
        PatientComboBoxModel patientComboBoxModel = new PatientComboBoxModel( pio.getPatientList() );
        jComboBox.setModel(patientComboBoxModel);
        jComboBox.setRenderer( new PatientListCellRenderer() );
        jComboBox.setEditable(true);
        // den Editor (das Textfeld) der ComboBox holen
        JTextField editor = (JTextField) jComboBox.getEditor().getEditorComponent();

        // diverse Listener hinzufügen
        jComboBox.addActionListener( e -> {
            /* Wenn die ComboBox editierbar ist, gibt getSelectedItem() oft nur einen String
             * (den getippten Text) zurück, statt des Patient-Objekts. Um das zu beheben,
             * fügen wir eine Logik ein, die beim Drücken von Enter das richtige Objekt auswählt:
             */
            Object selected = jComboBox.getSelectedItem();
            if (selected instanceof Patient) {
                Patient p = (Patient) selected;
                for (HasPatient u : user) {
                    u.setPatient(p);
                }
            }

            // wird von ENTER ausgelöst
            if ( e.getActionCommand().equals( "comboBoxEdited" )) {
                String text = editor.getText();
                patientComboBoxModel.filter(text);
                SwingUtilities.invokeLater( () -> {
                    Object firstMatch = patientComboBoxModel.getSelectedItem();
                    if (firstMatch != null) {
                        jComboBox.setSelectedItem(firstMatch);
                    }
                });
            }
        });
        editor.addMouseListener( new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                // bei Doppelklick Feld leeren
                if ( evt.getClickCount() >= 2 ) {
                    editor.setText("");
                }
            }
        });

        return patientComboBoxModel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BeratungsbogenButton;
    private javax.swing.JButton BindungserklärungButton;
    private javax.swing.JButton MehrkostenerklärungButton;
    private javax.swing.JRadioButton aRadioButton;
    private javax.swing.JPanel artikelPanel;
    private javax.swing.JButton deckblattButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton etikettenButton;
    private javax.swing.JCheckBox freiCheckBox;
    private javax.swing.JButton infoButton;
    private javax.swing.JTextField insurenceTextField;
    private javax.swing.JButton jAddArtikelButton;
    protected javax.swing.JComboBox<inko.Artikel> jArtikelComboBox;
    private javax.swing.JButton jBindFaelligButton;
    private javax.swing.JButton jButtonADG;
    private javax.swing.JButton jButtonArtikelListe;
    private javax.swing.JButton jButtonArtikelListe2;
    private javax.swing.JButton jButtonNewRx;
    private javax.swing.JButton jButtonSignBeratung;
    private javax.swing.JButton jButtonSignBindung;
    private javax.swing.JButton jButtonSignMehrkosten;
    private javax.swing.JButton jChangeArtikelButton;
    protected javax.swing.JButton jCreateArtikelButton;
    protected javax.swing.JButton jDownButton;
    private javax.swing.JButton jFaelligButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jLocationButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    protected javax.swing.JList<inko.Artikel> jPatientArtikelList;
    private javax.swing.JButton jRemoveArtikelButton;
    private javax.swing.JButton jRxFaelligButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    protected javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    protected javax.swing.JButton jUpButton;
    private com.toedter.calendar.JYearChooser jYearChooser;
    private javax.swing.JRadioButton kRadioButton;
    private javax.swing.JButton lieferlisteButton;
    private javax.swing.JCheckBox liefernCheckBox;
    private javax.swing.JButton newButton;
    private javax.swing.JComboBox<Patient> patientComboBox;
    private javax.swing.JPanel patientPanel;
    private javax.swing.JButton patientenlisteButton;
    private javax.swing.JCheckBox pauseCheckBox;
    private javax.swing.ButtonGroup radioGroup1;
    private javax.swing.JRadioButton sRadioButton;
    private javax.swing.JButton saveButton;
    protected gui.JAdvTextField statusField;
    // End of variables declaration//GEN-END:variables

}
